### ISSUE TITLE
Ruby error when converting clips from CODA 2.5.6

### ISSUE THREAD

**Issue by mortenfischer** [uetchy/clips2snippets#1]
Found Clip: 0C29D78A-BC3B-43BA-98D6-1BD9AA1738F7
/Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:78:in `[]=': index 73 out of string (IndexError)
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:78:in`block (3 levels) in gen'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:53:in `each'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:53:in`block (2 levels) in gen'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:33:in `each'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:33:in`each_with_index'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:33:in `block in gen'
    from /Users/mortenfischer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tmpdir.rb:88:in`mktmpdir'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/lib/clips2snippets/cli.rb:18:in `gen'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/gems/clips2snippets-0.0.1/bin/clips2snippets:5:in`<top (required)>'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/bin/clips2snippets:23:in `load'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/bin/clips2snippets:23:in`<main>'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/mortenfischer/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by uetchy** [comment]
I'm currently not using Coda; If you have any patch to fix them, feel free to open PR.
